# netlify.toml
[build]
  command = "pip install -r netlify/functions/recommend/requirements.txt -t netlify/functions/recommend/"
  publish = "."

[functions]
  directory = "netlify/functions"
  external_node_modules = []

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[build.environment]
  AWS_LAMBDA_JS_RUNTIME = "nodejs16.x"
  PYTHON_VERSION = "3.9"
