[
build
]
  command = "pip install -r requirements.txt"
  functions = "netlify/functions"
  publish = "/"

[
functions
]
  directory = "netlify/functions"
  included_files = ["model_prod.pkl"]

[[
redirects
]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
