[build]
  command = "cp model_prod.pkl netlify/functions/recommend/ && cp recommender.py netlify/functions/recommend/"
  publish = "."

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[build.environment]
  PYTHON_VERSION = "3.9"
