[build]
  command = """
    chmod +x netlify/functions/recommend/recommend.py && \
    pip install -r netlify/functions/recommend/requirements.txt -t netlify/functions/recommend/
  """
  publish = "."

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[build.environment]
  PYTHON_VERSION = "3.9"