[build]
  command = """
    curl -L https://raw.githubusercontent.com/netlify/build-image/focal/packages/python.sh | sh && \
    export PATH="/opt/buildhome/.python/bin:$PATH" && \
    pip install -r netlify/functions/recommend/requirements.txt -t netlify/functions/recommend/
  """
  publish = "."

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  external_node_modules = ["python-shell"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[build.environment]
  PYTHON_VERSION = "3.9"
