[build]
  command = ""
  publish = "."  # Use root directory since we don't have static assets

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[build.environment]
  PYTHON_VERSION = "3.9"
