[build]
  command = """
    cd netlify/functions/recommend && npm install && \
    pip install -r requirements.txt -t .
  """
  publish = "."

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[build.environment]
  PYTHON_VERSION = "3.9"
  NODE_VERSION = "16"
